# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=None)),
                ('date', models.DateField(default=None)),
            ],
        ),
    ]
